#!/usr/bin/env bash
# Regenerates assets/index.ts — one export per top-level raster image in
# assets/ (.png, .jpg, .jpeg, any capitalisation).
#
# assets/background/ is excluded: those files are referenced from CSS via
# url("@assets/background/…"), never imported.
#
# The file is fully rewritten, so it carries no hand-edits: drop an image in
# assets/ and re-run. Export names are the filename without extension, with
# anything that is not a valid identifier character replaced by "_".
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../assets"
export LC_ALL=C

shopt -s nullglob nocaseglob
files=(*.png *.jpg *.jpeg)
shopt -u nocaseglob

{
  echo "// Generated by scripts/update-assets-index.sh — do not edit by hand."
  for file in $(printf '%s\n' "${files[@]}" | sort); do
    name=${file%.*}
    name=${name//[^a-zA-Z0-9_]/_}
    # Leading digits and reserved words are not valid export names.
    case $name in
      [0-9]* | function | default | class | new | import | export | const | let | var | return | delete | in | do | if | typeof) name=_$name ;;
    esac
    echo "export { default as $name } from \"./$file\";"
  done
} > index.ts.new

# Validate before replacing the barrel, so a bad run leaves it untouched.
duplicates=$(sed -n 's/^export { default as \([^ ]*\) }.*/\1/p' index.ts.new | sort | uniq -d)
if [ -n "$duplicates" ]; then
  rm -f index.ts.new
  echo "Duplicate export names (rename the files):" >&2
  printf '  ! %s\n' $duplicates >&2
  exit 1
fi

mv index.ts.new index.ts
echo "assets/index.ts: $(grep -c '^export ' index.ts) exports."
